version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-stretch-browsers

    working_directory: ~/aqapython

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            curl -o allure-2.7.0.zip -Ls https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.zip
            unzip allure-2.7.0.zip
            export PATH=$PATH:$(pwd)/allure-2.7.0/bin/
            echo "export PATH=$PATH:$(pwd)/allure-2.7.0/bin/" >> $BASH_ENV
            allure --version

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # chmod +x phase1/src/fibonacci/fibonacci.py
            # phase1/src/fibonacci/fibonacci.py
            chmod +x drivers/linux/chromedriver
            pytest -n4 --reruns 2 -v -l --alluredir=test_results
          when: always

      - run:
          name: generate report
          command: |
            allure generate --clean test_results
          when: always

      - store_artifacts:
          path: allure-report

