version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-stretch-browsers

    working_directory: ~/aqapython

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt-add-repository ppa:qameta/allure
            sudo apt-get install allure

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # chmod +x phase1/src/fibonacci/fibonacci.py
            # phase1/src/fibonacci/fibonacci.py
            chmod +x drivers/linux/chromedriver
            pytest tests/phase4/test_web_login.py -n4 --reruns 2 -v -l --alluredir=test_results

      - run:
          name: generate report
          command: |
            allure generate --clean test_results

      - store_artifacts:
          path: allure-report/index.html
          destination: allure-report

