version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-stretch-node-browsers
    working_directory: ~/aqapython
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - store_artifacts:
          path: test_reports
          destination: test_reports